### PR TITLE
Cycle list of fens more smoothly with --forever

### PR DESCRIPTION
**Pull request by vondele**
Basically, ensure sufficient work is always in the queue, starting to queue fens of the next depth before all are finished of the current depth.

This now uses a fixed list of fens, i.e. no reloading on cycling (this could be re-added if useful).

### CODE REVIEW

**Comment by robertnurnberg** [comment]
I have played around with this a bit, works great as far as I can tell. Ready to be merged.

I may introduce a `--reload` option for the old file loading behaviour in a follow-up PR, if you don't mind.

**Comment by vondele** [comment]
yes, I think it is relatively easy to introduce a reload, needs some care as the epds list is being referenced (e.g. len(epds)). Probably one could factor out the file parsing code in a little subroutine. 

I have also been wondering if there should be an option to deal with pgns a bit more broadly, e.g. have all positions in the pgn added to the epds list, or e.g. the first plies?

**Comment by robertnurnberg** [comment]
Agreed. Smells like more command line options to me. :) May look into adding those soon-ish.

**Comment by robertnurnberg** [comment]
I noticed a bug with this @vondele .

Trying to implement a `--reload` option I noticed that the current code with `--forever` leads to an evergrowing `tasks` list. I assume this behaviour is unintended. It can be easily spotted with some print statements. Basically, `epdIdx` gets repeatedly set to zero, and the queue size is always at 5 < 8 (for default concurrency).

Do you manage to fix this?

**Comment by vondele** [comment]
I'll have a look.

**Pull request merged**
