### PR TITLE
Put a semaphore around queryall

### PR DESCRIPTION
**Pull request by vondele**
This limits the number of threads waiting for requests to complete, reducing the number of api calls earlier in case the rate limiting hits.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
I am not sure how much this PR will help. Our only interaction with cdb is through `__cdbapicall`, which is behind a semaphore with the given `--concurrency`. 

I think once we hit the rate limit, that is a sign that our concurrency is too large (for the resources available to our IP address at the moment, and for the currently observed cdb response times). Limiting the number of threads that can await on  `__cdbapicall` (or sleep) concurrently does not seem to address that.

But it is possible that I am missing something in between how the cdb-side throttling and your PR work together.

**Comment by vondele** [comment]
The current semaphore limits the concurrent access to the api. That's a good hard limit. If we assume that a typical api call takes 300ms, we can have at most 3.3 * concurrency calls per second. 

Now, if this hits the rate limit nevertheless, calls start failing, and threads go to sleep and call the api again later. However, the number of threads that can call the api and go to sleep can be very large without this patch (something like 4 * concurrency * max_level). With 1000s of such sleeping threads waking up every say 10s, the rate of api calls from these 'sleepy' threads is still large. This patch limits the number of threads that can go to sleep to something like 4 * concurrency.

**Comment by robertnurnberg** [comment]
Thanks for the explanation. I think I can follow you. So this PR in effect achieves something similar to what I had intended with longer `timeout` sleeping times. But more elegant. :) So I am happy to see this merged.

Two comments: where do you take the 300ms number from? Is that something you see typically on your hw? I searched in my grobtrack data and found this in today's cdbbulksearch run:
```
Search at depth  4
  cdb PV len:  10
  score     :  9
  PV        :  d6c5 e3c4 g5e7 e2d2 e7g5 d2e2 g5f6 e2d2 f6g7 d2c2 g7f6 c2d2 c5c6 g3g4 h7h5
  PV len    :  15
  level     :  21
  max level :  22
  queryall  :  955
  bf        :  5.56
  chessdbq  :  250 (26.18% of queryall)
  enqueued  :  0
  requeued  :  1
  unscored  :  0 (0.00% of enqueued)
  reprobed  :  25 (10.00% of chessdbq)
  inflightQ :  34.45
  inflightR :  8.80
  cdb time  :  32
  date      :  2023-07-03T11:05:55.492149
  total time:  0:00:08.14
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_0_1_moves_b1a3_e7e5_a3c4_b8c6_e2e4_g8f6_d2d3_d7d5_e4d5_f6d5_g1f3_d8e7_c2c3_c8f5_c4e3_d5e3_c1e3_e8c8_d1a4_f5d7_e1c1_a7a6_a4c2_d7e6_a2a3_g7g6_g2g3_e6d5_f1g2_f8g7_h1e1_f7f5_f3h4_e7f7_g2d5_f7d5_f2f4_g7f6_h4g2_d5a2_c2b1_a2f7_b1c2_h8e8_f4e5_c6e5_c1b1_e5g4_e3g1_e8e1_d1e1_g4e5_d3d4_e5f3_e1f1_f3g1_f1g1_d8e8_g1e1_e8e7_c2d3_e7e1_g2e1_f7d5_d3e3_d5e4_e3e4_f5e4_b1c2_c8d7_e1g2_d7e6_a3a4_f6g5_c2d1_e6d6_b2b3_c7c5_d4c5_d6c5_d1e2_g5f6_e2d2_c5d6_g2e3_f6g5_d2e2_d6c5_e3c4_g5e7_e2d2_e7g5_d2e2_g5f6_e2d2_f6g7_d2c2_g7f6_c2d2_c5c6_g3g4_h7h5
```  

I guess this was a lucky fluke, but I regularly see around 50-60ms. Nevertheless, in your calculation that would mean we can have up to at most 33 * concurrency calls per second. Agreed?

And secondly, if `--concurrency` is set too high from the onset, something crazy like 1000, then this PR will not help much. But I think here we would blame the user for inappropriate settings.

**Comment by vondele** [comment]
Do you refer to `cdb time  :  32` ? That time is already using the concurrency. So this number would suggest this script has about 1000/32 calls per second to the api.

The time I refer to is based on what I measure for a single API call:
time wget api-url
In reality the script should be doing somewhat better as the session that is created should be persistent.

**Comment by robertnurnberg** [comment]
Yeah, I was trying to follow your calculations that led to "3.3 * concurrency calls per second". If we take the `32ms` per api call at face value, then this potential maximum rate could be much higher.

In other news, I have tested this patch and running five instances in parallel over 8 hours "only" gives about 100 `Rate limit exceeded` errors now, down from about 700 in 5 hours in my discord message. So I think it's worth merging.

**Pull request merged**
