### PR TITLE
shorten reprobe_PV

### PR DESCRIPTION
**Pull request by robertnurnberg**
So I somehow managed to delete the branch the old PR https://github.com/vondele/cdbexplore/pull/51 was based on. :(

So reopening here. These are provisional stats:
```
Search at depth  24
  cdb PV len:  84
  score     :  143
  PV        :  d7d5 f1g2 c8g4 c2c4 c7c6 d1b3 e7e6 b3b7 b8d7 b1c3 g8e7 c4d5 e6d5 d2d4 a8b8 b7a6 h7h6 g1f3 b8b6 a6a7 e7g6 a7a4 f8b4 a2a3 b4d6 h2h4 g4h5 e1f1 e8g8 a1a2 f8e8 b2b4 b6b8 a4c2 b8a8 g2h3 a8a7 h3g2 d8e7 c3d1 e7d8 d1c3 d8e7 c3d1
  PV len    :  44
  max ply   :  121
  queryall  :  2043896
  reprobe queryall  :  28430
  reprobe queryall2 :  20029
  bf        :  1.83
  inflightR :  13.95
  inflightQ :  287.45
  chessdbq  :  447229
  enqueued  :  38090
  unscored  :  19714
  date      :  2023-06-05T00:17:49.244179
  total time:  3:40:29.45
  cdb time  :  29
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_moves_g2g4_d7d5_f1g2_c8g4_c2c4_c7c6_d1b3_e7e6_b3b7_b8d7_b1c3_g8e7_c4d5_e6d5_d2d4_a8b8_b7a6_h7h6_g1f3_b8b6_a6a7_e7g6_a7a4_f8b4_a2a3_b4d6_h2h4_g4h5_e1f1_e8g8_a1a2_f8e8_b2b4_b6b8_a4c2_b8a8_g2h3_a8a7_h3g2_d8e7_c3d1_e7d8_d1c3_d8e7_c3d1
```

28430 / 447229 = 6.36%, and 28430 / 20029 = 142%.

I think these numbers could justify merging this, in particular because no information is lost for cdb (in the "twig" A->B->C, the reprobing called for A will pick up any information that was relayed to B from C, and then to A from B).

Of course, before merging I would remove the two counters again.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Another example, from a different (shorter) search: `python cdbsearch.py --epd "3rr1k1/bpp2qp1/p1pn1p1p/P6b/1PPP4/4BN1P/2QN1PPK/2R1R3 b - - 3 25"`

```
Search at depth  17
  cdb PV len:  35
  score     :  -24  
  PV        :  b7b6 c4c5 d6b5 f3h4 f6f5 h4f5 h5g6 g2g4 g6f5 g4f5 b5d4 e3d4 e8e1 c1e1 d8d4 d2f3 d4f4 f3e5 f7f5 c2f5 f4f5 e1e2 b6a5 e5c6 f5f6 c6a5 g8f8 h2g2 a7b8 e2e3 f6g6 g2f1 c7c6 a5b3 b8f4 e3e1 g6f6 e1a1 f4e5
  PV len    :  39
  max ply   :  58
  queryall  :  21123
  reprobe queryall  :  852
  reprobe queryall2 :  850
  bf        :  1.80
  inflightR :  9.28
  inflightQ :  214.47
  chessdbq  :  7872
  enqueued  :  1660
  unscored  :  1015
  date      :  2023-06-06T11:03:04.925344
  total time:  0:15:53.99
  cdb time  :  121
  URL       :  https://chessdb.cn/queryc_en/?3rr1k1/bpp2qp1/p1pn1p1p/P6b/1PPP4/4BN1P/2QN1PPK/2R1R3_b_-_-_3_25_moves_b7b6_c4c5_d6b5_f3h4_f6f5_h4f5_h5g6_g2g4_g6f5_g4f5_b5d4_e3d4_e8e1_c1e1_d8d4_d2f3_d4f4_f3e5_f7f5_c2f5_f4f5_e1e2_b6a5_e5c6_f5f6_c6a5_g8f8_h2g2_a7b8_e2e3_f6g6_g2f1_c7c6_a5b3_b8f4_e3e1_g6f6_e1a1_f4e5
  ```
  
Here 852 / 7872 = 10.8%, showing once again the high proportion of reprobe API calls. (Maybe apart from merging this PR, we could think of reducing this load in other ways: increasing `depthReprobePV` is one, calling `reprobe_PV` only for the root node on completion of a depth search another (more drastic) one.)

**Comment by vondele** [comment]
so, based on this stats, I would suggest to indeed increase depthReprobePV, maybe you could find a reasonable number that leads to e.g. less than 1% of reprobePV queries. I would like to continue to reprobe to the startpos, this is typically only a small part of the reprobing load.

My gut feeling would suggest not to merge this PR, this is too much of an implementation detail to expose this to the user. But I'm happy to be convinced otherwise.

**Comment by robertnurnberg** [comment]
Ok, I will try to convince you. ;)

But maybe first I need to better understand what purpose `reprobe_PV` is fulfilling. I seem to remember a discussion on discord that long running `cdbsearch` instances will diverge from cdb, because cdb is unaware of the local progress. So is the aim to keep cdb informed about new discoveries of the local search?

Or is it also to somehow improve future local searches?

**Comment by vondele** [comment]
The purpose is to Ensure progress made in a local search is reflected at the root. For this, it is enough if this update is every few minutes.

**Comment by robertnurnberg** [comment]
I must admit this is one part of the code I do not fully understand, so sorry for being slow. When you say "reflected at the root", do you mean at the root on cdb? Because the mini-max algo always brings any local search progress to the root, once the search for the depth is completed, does it not?

So in simple terms, what would be the (negative) effects of doing `reprobe_PV` only upon completion of a depth search, and only for the PV of the root pos?

**Comment by vondele** [comment]
yes, the root at cdb. The local search is always OK. 

Doing this only upon completion and only for the PV of the rootpos makes it much more likely that the found PV is not reflected at cdb (i.e. if another line seems favorable to cdb, but refuted locally, that would not show up). There is of course no guarantee that the reprobing fixes that, but it makes it more likely.

**Comment by robertnurnberg** [comment]
Great, thanks. That is exactly what I thought so far. Will check with noob on sf-discord how cdb's own back propagation works precisely.

**Comment by robertnurnberg** [comment]
Hm, so noob's latest reply on [discord](https://discord.com/channels/435943710472011776/1101022188313772083/1115964824858398762) seems to indicate that all we need to do is call e.g. `querypv` for the _leaf_ node of a PV we want to update on cdb, and cdb will do this all by itself. Still awaiting his reply of our long that would usually take, but this may then be an option (c)?

**Comment by robertnurnberg** [comment]
Just for completeness, the final update. (I have stopped that search now.)
```
Search at depth  30
  cdb PV len:  27
  score     :  145
  PV        :  d7d5 e2e3 e7e5 d2d3 c8e6 a2a3 b8c6 f1e2 g7g6 b2b4 f8g7 h2h4 h7h6 b4b5 c6e7 g1f3 d5d4 c1b2 c7c5 b1d2 e7d5 d2c4
  PV len    :  22
  max ply   :  121
  queryall  :  91924087
  reprobe queryall  :  217866
  reprobe queryall2 :  158660
  bf        :  1.84
  inflightR :  12.92
  inflightQ :  213.66
  chessdbq  :  2795158
  enqueued  :  539742
  unscored  :  269324
  date      :  2023-06-07T18:29:46.800748
  total time:  2 days, 21:52:27
  cdb time  :  89
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_moves_g2g4_d7d5_e2e3_e7e5_d2d3_c8e6_a2a3_b8c6_f1e2_g7g6_b2b4_f8g7_h2h4_h7h6_b4b5_c6e7_g1f3_d5d4_c1b2_c7c5_b1d2_e7d5_d2c4
```
With 217866 / 2795158 = 7.8% and 217866 / 158660 = 137%.

I believe the way forward is to replace `reprobe_PV` with a new method that simply does a `queue` for the leaf node of the PV. I can create a PR if you agree.

**Comment by robertnurnberg** [comment]
Closing in favour of https://github.com/vondele/cdbexplore/pull/62.

A flaw in the proposed setup is that we cannot guarantee sequential execution of the individual `repobe_PV` runs, so the argument for the twig A->B->C breaks down.

**Pull request closed without merging**
