### PR TITLE
Properly count number of unfinished tasks

### PR DESCRIPTION
**Pull request by vondele**
rather than relying on the (incorrect) internals of the process pool, do proper accounting.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Looks good, thanks.

**Comment by vondele** [comment]
btw, you should now be able to squash and merge PRs as well.

**Comment by robertnurnberg** [comment]
I saw, thanks a lot. Not sure how squash works, and worried I may break something. So may stay with old routine for a while yet. :)

**Comment by vondele** [comment]
On the github webinterface you can select 'squash and merge' ... just clicking there normally will work, if the patch is up-to-date with master. Try it with a simple patch first :-)

**Comment by robertnurnberg** [comment]
I take it there is no squashing without merging? E.g. for https://github.com/vondele/cdbexplore/pull/42 it may be nicer for you to see all my changes in a single commit?

**Comment by vondele** [comment]
yes, you can rebase your commits in a branch on main `git rebase -i main`  and after that force push your branch `git push origin +branchname` (mind the `+`).

**Comment by robertnurnberg** [comment]
Hm, I tried the first command just now, after merging https://github.com/vondele/cdbexplore/pull/45 into main on your repo. Then I synced main on my fork with yours (via the web interface), pulled into my local main, changed into the branch locally and executed your command `git rebase -i main`. Then I got a text file to edit with a list of commits in that branch so far, I think. I did not change anything and saved, but then I got some error. So I aborted the whole process.

Incidentally, after I synced main on the web, I usually also sync all active branches in my fork on the web. Is that correct? And finally, can I do this syncing easily on the command line?

**Pull request merged**
