### PR TITLE
shorten reprobing of PV

### PR DESCRIPTION
**Pull request by robertnurnberg**
I put this in draft for now to hear your comments first.

I believe the current `reprobe_PV` does a lot of unnecessary and repeated querying of the API, because it goes _all the way back to the root_ position for _every_ PV in the search tree that reaches the triggering length. For long-term explorations that means a lot of duplication.

The proposed variant just does reprobing of the PV from the leaf to the node that triggered the call, so includes the querying of the node itself (hence the `range(pvlen + 1)`. I believe the new information will reach the root on cdb eventually, through calls to `reprobe_PV` by the root and nodes close to the root.

On top of that the PR introduces the two depth constants for better clarity. The constant related to scoring unscored moves is increased in line with the discussion in https://github.com/vondele/cdbexplore/issues/50.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
As I will be afk for the next few days, I changed this ready to review, so that you can decide how to proceed with this.

**Comment by vondele** [comment]
The reprobing back to root was on purpose, to kind of ensure the results of the work propagate back to the root. I would say this is really relatively infrequent (a d15 search takes typically minutes), so we're adding a handful of queries every few minutes to cdb, not a relevant load. It is also non-blocking for cdbsearch. As such I would continue to go back to root. The other cleanups are fine with me (including moving the magic constants/parameters up).

**Comment by robertnurnberg** [comment]
Gotta run to catch a train, I hope the latest change means we can do both: ensure propagation back to root and fewer repeated API calls. (The latter I think becomes an issue with, say, depth 40 searches on grob?. Imagine how many times 1.g4 d5 will be queried via API with a large tree.)

So, the latest change means in the "twigg" A->B->C, if C calls `reprobe_PV` then the probing goes to B. As C was reached in search from B, and it's depth cannot be bigger than B's, `reprobe_PV` will be called from B once `search` recursion goes up in tree again. That means the new information from C and it's PV will reach root, and not later than the global `search` call in the outer `while` loops terminates.

**Comment by vondele** [comment]
I still would prefer to probe back to root. I assume these are very few queries compared to the queries to do a d15 search (like < 0.1%). Maybe you can do a measurement to if this would not be the case?

**Comment by robertnurnberg** [comment]
Ok, are the two introduced counters what you had in mind? We could compare them with each other, and with the total `queryall` counter. If you agree, I can start some long-term test run.

**Comment by vondele** [comment]
yes, these two counters could be used to check, and especially be compared to the total queryall number.

**Comment by robertnurnberg** [comment]
Ok, I have started such a test run. Here is an early output:
```
Search at depth  21
  cdb PV len:  75
  score     :  147
  PV        :  d7d5 e2e3 b8c6 d2d4 e7e5 b1c3 c8e6 h2h3 h7h5 g4h5 g8f6 f1b5 e5e4 b5c6 b7c6 d1e2 h8h5 c1d2 a7a5 e1c1 a5a4 c1b1 d8b8 b1a1 a4a3 b2b3 g7g6 e2f1 f8e7 d1b1 b8c8 c3e2 h5h8
  PV len    :  33
  max ply   :  121
  queryall  :  478152
  reprobe queryall  :  2733
  reprobe queryall2 :  2553
  bf        :  1.86
  inflightR :  13.56
  inflightQ :  262.69
  chessdbq  :  114419
  enqueued  :  4815
  unscored  :  2074
  date      :  2023-06-04T21:36:42.197209
  total time:  0:59:22.40
  cdb time  :  31
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_moves_g2g4_d7d5_e2e3_b8c6_d2d4_e7e5_b1c3_c8e6_h2h3_h7h5_g4h5_g8f6_f1b5_e5e4_b5c6_b7c6_d1e2_h8h5_c1d2_a7a5_e1c1_a5a4_c1b1_d8b8_b1a1_a4a3_b2b3_g7g6_e2f1_f8e7_d1b1_b8c8_c3e2_h5h8
  ```
  
So `chessdbq  :  114419` vs `reprobe queryall  :  2733`, so about 2.4%. But I would like to run it for much longer, and will update the states here after a few days.

**Pull request closed without merging**
